### ISSUE TITLE
Not able to redirect to the desktop version on mobile site (Adidas mWeb)

### ISSUE THREAD

**Issue by anurag216** [adidas/adidas-contribution-guidelines#3]
Steps to reproduce:
1. Go to URL: 'https://m.shop.adidas.co.in/'
2. Go to the footer section.
3. Click on the button 'View desktop version' => selector: 'a[href="http://shop.adidas.co.in/?source=mobile"]' 
4. Stays on the same mobile site and loads just the main footer => selector:'div[id="adi-mainfooter"]'

Device used:
iPhone X

Screenshot:
![image](https://user-images.githubusercontent.com/35896405/90048060-92b7c400-dcf0-11ea-973c-9df6dd9692f9.png)

**Comment by RecuencoJones** [comment]
Hi @anurag216, thanks for reporting!
However, I don't think this issue belongs here... I'll pass it on to my colleagues so they can verify.

**Comment by anurag216** [comment]
What'd have been the right place to report this? @RecuencoJones
