### ISSUE TITLE
Replace mention of `tslint-config-adidas` in the TypeScript coding guidelines with `eslint-config-adidas-typescript`

### ISSUE THREAD

**Issue by ClaudioHoffmann** [adidas/adidas-contribution-guidelines#4]
[TSLint has been deprecated since 2019.](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) The `js-linter-configs team` actually was aware of this and [ported the TypeScript rules to ESLint](https://github.com/adidas/js-linter-configs/tree/master/packages/eslint-config-adidas-typescript), but the wiki page still only links the TSLint-based one. 

(Also, maybe consider that blocking public editing of wikis defeats the entire point of a wiki. If you want to force changes to go through a proper review process, committing the documentation as Markdown files to the repository is the right way to go.)

**Comment by moelders** [comment]
Hello @ClaudioHoffmann, thank you for notifying us. I already updated the page with the documentation. Thank you very much!

I understand your point, and of course, being as part of the Wiki does not allow contributors to open a pull-request, only to open an issue. We are going to think about moving it to the repository files.

Thank you again.
